# -*- coding: utf-8 -*-
"""AIQuiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n17_-IFUaCMZ74fTj6BYr7ZG3tma644t
"""

# 🚀 Install Dependencies
!pip install transformers accelerate torch gradio

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import gradio as gr

# 🔹 Load Open-Source LLM (Microsoft Phi-2, Fully Open)
MODEL_NAME = "microsoft/phi-2"

# ✅ Load Tokenizer & Model
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, torch_dtype=torch.float16, device_map="auto"
)

# 🔹 Function to Generate Assignment Questions
def generate_questions(topic, num_questions=5):
    prompt = f"Generate {num_questions} assignment questions about {topic}. Include MCQs and short-answer questions."

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    output_ids = model.generate(inputs.input_ids, max_new_tokens=150, temperature=0.7)
    response = tokenizer.decode(output_ids[0], skip_special_tokens=True)

    return response

# 🔹 Create Gradio Web UI
iface = gr.Interface(
    fn=generate_questions,
    inputs=[gr.Textbox(label="Enter Topic"), gr.Slider(1, 10, value=5, label="Number of Questions")],
    outputs="text",
    title="📘 AI Assignment Question Generator",
    description="Enter a topic, and the AI will generate assignment questions!"
)

# ✅ Launch Web App
iface.launch(share=True)